version: "3"
services:
  backend:
    build:
      context: ./bin/docker/php
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:9003:9000" #fastcgi
    working_dir: /app
    image: laravel/app
    restart: always
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.7
    ports:
      - "127.0.0.1:3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=root
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=pws_db
    restart: always

  nginx:
    build:
      context: ./bin/docker/nginx
    ports:
      - "127.0.0.1:8090:80"
    depends_on:
      - backend
    volumes:
      - .:/app
    restart: always


networks:
  default:
    name: pws-network


