openapi: 3.0.3
info:
  title: pws
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://file-ws.test'
paths:
  /api/files:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters:
        -
          in: query
          name: order_id
          description: 'required_without:session_id The ID of the order.'
          example: '1'
          required: false
          schema:
            type: string
            description: 'required_without:session_id The ID of the order.'
            example: '1'
            nullable: false
        -
          in: query
          name: file_type
          description: 'The type of the file.'
          example: invoice
          required: true
          schema:
            type: string
            description: 'The type of the file.'
            example: invoice
            nullable: false
        -
          in: query
          name: session_id
          description: 'required_without:order_id The session ID.'
          example: abc123
          required: false
          schema:
            type: string
            description: 'required_without:order_id The session ID.'
            example: abc123
            nullable: false
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 1
                      user_id: 1
                      order_id: 1
                      file_name: example.pdf
                      file_path: path/to/example.pdf
                      file_type: invoice
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        user_id: 1
                        order_id: 1
                        file_name: example.pdf
                        file_path: path/to/example.pdf
                        file_type: invoice
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        user_id:
                          type: integer
                          example: 1
                        order_id:
                          type: integer
                          example: 1
                        file_name:
                          type: string
                          example: example.pdf
                        file_path:
                          type: string
                          example: path/to/example.pdf
                        file_type:
                          type: string
                          example: invoice
      tags:
        - 'File Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                order_id:
                  type: string
                  description: 'This field is required when <code>session_id</code> is not present.'
                  example: null
                  nullable: false
                file_type:
                  type: string
                  description: ''
                  example: fugiat
                  nullable: false
                session_id:
                  type: string
                  description: 'This field is required when <code>order_id</code> is not present.'
                  example: null
                  nullable: false
              required:
                - file_type
      security: []
  '/api/file/{fileId}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    user_id: 1
                    order_id: 1
                    file_name: example.pdf
                    file_path: path/to/example.pdf
                    file_type: invoice
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      user_id:
                        type: integer
                        example: 1
                      order_id:
                        type: integer
                        example: 1
                      file_name:
                        type: string
                        example: example.pdf
                      file_path:
                        type: string
                        example: path/to/example.pdf
                      file_type:
                        type: string
                        example: invoice
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Found'
                properties:
                  message:
                    type: string
                    example: 'Not Found'
      tags:
        - 'File Management'
      security: []
    parameters:
      -
        in: path
        name: fileId
        description: 'The ID of the file.'
        example: 1
        required: true
        schema:
          type: integer
  /api/files/upload:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'invoice files uploaded successfully'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'invoice files uploaded successfully'
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'No file uploaded'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'No file uploaded'
      tags:
        - 'File Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: 'The ID of the user.'
                  example: 1
                  nullable: false
                order_id:
                  type: integer
                  description: 'The ID of the order.'
                  example: 1
                  nullable: false
                session_id:
                  type: string
                  description: 'The session ID.'
                  example: 53fc529b-f438-49cc-8e42-959400cbd1c1
                  nullable: true
                file_type:
                  type: string
                  description: 'The type of the file.'
                  example: invoice
                  nullable: false
                files:
                  type: array
                  description: 'The files to be uploaded.'
                  example:
                    - dicta
                  items:
                    type: string
                base64_files:
                  type: array
                  description: 'The base64 encoded files to be uploaded.'
                  example:
                    - consequatur
                  items:
                    type: string
              required:
                - user_id
                - order_id
                - file_type
      security: []
  /api/move/temp/to/permanent:
    post:
      summary: 'Move files to permanent storage.'
      operationId: moveFilesToPermanentStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Files moved to permanent storage successfully'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Files moved to permanent storage successfully'
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Validation error'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Validation error'
      tags:
        - 'File Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session_id:
                  type: string
                  description: 'The session ID.'
                  example: abc123
                  nullable: false
                order_id:
                  type: integer
                  description: 'The ID of the order.'
                  example: 1
                  nullable: false
                user_id:
                  type: integer
                  description: 'The ID of the user.'
                  example: 1
                  nullable: false
                file_type:
                  type: string
                  description: 'The type of the file.'
                  example: invoice
                  nullable: false
              required:
                - session_id
                - order_id
                - user_id
                - file_type
      security: []
  /api/temp/files/upload:
    post:
      summary: 'Temporarily store a newly created resource in storage.'
      operationId: temporarilyStoreANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'invoice files uploaded temporarily with session ID'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'invoice files uploaded temporarily with session ID'
        400:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'No file uploaded'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'No file uploaded'
      tags:
        - 'File Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  description: 'The ID of the user. This field is required when <code>session_id</code> is not present.'
                  example: 1
                  nullable: false
                order_id:
                  type: string
                  description: 'The ID of the order. This field is required when <code>session_id</code> is not present.'
                  example: 1
                  nullable: false
                session_id:
                  type: string
                  description: 'The session ID.'
                  example: abc123
                  nullable: true
                file_type:
                  type: string
                  description: 'The type of the file.'
                  example: invoice
                  nullable: false
                files:
                  type: array
                  description: 'The files to be uploaded.'
                  example:
                    - autem
                  items:
                    type: string
                base64_files:
                  type: array
                  description: 'The base64 encoded files to be uploaded.'
                  example:
                    - odit
                  items:
                    type: string
              required:
                - session_id
                - file_type
      security: []
  '/api/download/{file_id}':
    get:
      summary: 'Download the specified resource.'
      operationId: downloadTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'application/octet-stream The file download.'
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Found'
                properties:
                  message:
                    type: string
                    example: 'Not Found'
      tags:
        - 'File Management'
      security: []
    parameters:
      -
        in: path
        name: file_id
        description: 'The ID of the file.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: file
        description: 'The ID of the file.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/file/destroy/{file_id}':
    post:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses:
        204:
          description: ''
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Not Found'
                properties:
                  message:
                    type: string
                    example: 'Not Found'
      tags:
        - 'File Management'
      security: []
    parameters:
      -
        in: path
        name: file_id
        description: 'The ID of the file.'
        example: 1
        required: true
        schema:
          type: integer
      -
        in: path
        name: file
        description: 'The ID of the file.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: 'File Management'
    description: ''
